name: One-Time Push to nest_next_copilot

on:
  workflow_dispatch:

jobs:
  push-to-nest-next-copilot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to nest_next_copilot main branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Or use GH_PAT if you set up a PAT secret
        run: |
          git remote add dest https://x-access-token:${GH_TOKEN}@github.com/abdoElHodaky/nest_next_copilot.git
          git push dest main --force
